title: Creating a Release Based Workflow
tagline: Learn and practice a workflow based around creating releases on GitHub.
description: This course focuses on releases, and more complex branching strategies.
tags:
  - GitHub
template:
    name: release-based-workflow
    repo: release-workflow-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.1_welcome.md
  - type: octokit
    method: projects.createRepoProject
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    name: Release 2.0
    body: This project board tracks the steps necessary for Release 2.0.

steps:
  #1
  - title: Add a tag
    description: Add a tag to the most recent commit on the master branch.
    event: release.published
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        issue: Welcome
        with: 01.1_more-about-tags.md
        data:
          url: '{{ repoURl }}/releases'

  #2
  - title: Close the first issue
    description: Now that the first release has been created, close the first issue.
    event: issues.closed
    link: '{{ repoUrl }}/issue/1'
    actions:
      - type: createIssue
        title: Bug found, please fix
        body: 02.1_bug-issue.md
        action_id: bugIssue
      - type: respond
        with: 02.2_next-step.md
        data:
          url: '%actions.bugIssue.data.html_url%'

  #3
  - title: Fix the bug
    description: Create a branch, fix the bug, and open a pull request.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: createReview
        body: 03.1_request-changes.md
        event: REQUEST_CHANGES

  #4
  - title: Create a release branch
    description: Create a release branch that will represent work for a specific release.
    event: create
    link: '{{ repoURL }}/pull/3'
    actions:      #store the branch name for use in step 7
      - type: respond
        with: 04.1_release-branch.md
        issue: 3

  #5
  - title: Edit a pull request
    description: Edit the pull request to introduce the bug fix into the release branch.
    event: pull_request.edited
    link: '{{ repoURL }}/pull/3'
    actions:
      - type: removeBranchProtection
      - type: respond
        with: 05.1_merge.md

  #6
  - title: Merge the pull request
    description: Merge the pull request to update the release branch.
    event: pull_request.closed
    link: '{{ repoURL }}/pull/3'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 06.1_early-close.md
      - type: createIssue
        title: Managing releases
        body: 06.2_managing-releases.md
        action_id: releaseIssue
      - type: respond
        with: 06.3_nice-merge.md
        data:
          url: '%actions.releaseIssue.data.html_url%'

  #7
  - title: Add to the project board
    description: Add a card to the "in progress" column of the project board.
    event: project_card.created
    link: '{{ repoURL }}/projects/1'
    actions:
      - type: respond
        body: 07.1_project.md
        issue: Managing releases
      - type: createPullRequest
        title: Merge the release branch into master
        body: 07.3_bot-pr.md
        head: v1.0 #for testing purposes only, should be replaced by variable in step 4

  #8
  - title: Approve a pull request
    description: Review and approve the pull request that Learning Lab opened.
    event: pull_request_review.submitted
    link: '{{ repoURL }}/pull/5'
    actions:
      # - type: gate #make sure it was approval
      - type: mergePullRequest
      - type: CreateIssue
        title: Creating a release
        body: 08.1_create-release.md
        action_id: nextIssue
      - type: respond
        with: 8.2_point-to-issue.md
        data:
          url: '%actions.nextIssue.data.html_url%'

  #9
  - title: Create a final release & changelog
    description: Create a release with the most recent code, and craft release notes as a changelog.
    event: release.published
    link: '{{ repoURL }}/issues/6'
    actions:
      - type: respond
        with: 09.1_congratulations.md
