title: Creating a Release Based Workflow
tagline: Learn and practice a workflow based around creating releases on GitHub.
description: This course focuses on releases, and more complex branching strategies.
tags:
  - GitHub
template:
    name: release-based-workflow
    repo: AlienInvasion
before:
  # enable branch protection
  - type: updateBranchProtection
  # creating a welcome issue that will have the user's first instructions
  - type: createIssue
    title: Welcome
    body: 00.1_welcome.md

steps:

  #1 - ask the user to create a beta release from the most recent commit on master
  - title: Create a beta release
    description: Create a beta release, or a pre-release, from the existing codebase.
    event: release.published
    link: '{{ repoUrl }}/issues/1'
    actions:
      # creates an issue with the next instructions about project boards
      - type: createIssue
        title: Organizing a release
        body: 01.1_project-board.md
        action_id: trackingIssue
      # responding in the first welcome issue, pointing the user to the next issue just created
      - type: respond
        issue: Welcome
        with: 00.2_next-step.md
        data:
          url: '%actions.trackingIssue.data.html_url%'
          releases: '{{ repoURl }}/releases'
      # closes the welcome issue
      - type: closeIssue
        issue: Welcome

  #2 - The user should create a project board
  - title: Prepare for the next release
    description: Create a project board.
    event: project.created
    link: '{{ repoUrl }}/issues/2'
    actions:
    - type: respond
      issue: Organizing a release
      with: 01.2_project-column.md

  #3 - The user should create a project column
  - title: Adding columns
    description: Create a project column.
    event: project_column.created
    link: '{{ repoUrl }}/issues/2'
    actions:
    - type: respond
      issue: Organizing a release
      with: 01.3_move-a-card.md

  #4 - The user should add a card to the project board
  - title: Triaging issues
    description: Add an issue to a project column.
    event: project_card.created
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: createIssue
        title: Creating a release branch
        body: 02.1_release-branches.md
        action_id: branchPrompt
    # TODO: Add branch validation
      - type: respond
        with: 01.4_projects-success.md
        issue: Organizing a release
        data:
          url: '%actions.branchPrompt.data.html_url%'

  #5 - The user should create a release branch
  - title: Branching strategies
    description: Create a release branch.
    event: create
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: updateBranchProtection
        branch: release-v1.0
      # creating a third issue for the user, asking them to go through the GitHub flow to make a change
      - type: createIssue
        title: Please fix this bug
        body: 03.1_update-readme.md
        action_id: fixbugIssue
      - type: respond
        issue: Creating a release branch
        with: 02.2_branch-success.md
        data:
          url: '%actions.fixbugIssue.data.html_url%'
      - type: closeIssue
        issue: Creating a release branch

  #6 - User creates a branch making a change and opens a pull request against `base: release-v1.0`
  - title: Adding a feature
    description: Create a branch, update the README.md, and open a pull request.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/3'
    actions:
      # We make sure that the user's pull request has the base set to `release-v1.0`
      - type: gate
        left: '%payload.pull_request.base.ref%'
        operator: ===
        right: 'release-v1.0'
        # If the user opened a pull request to master instead...
        else:
          # we comment and tell them that they should try again
          - type: respond
            with: 03.2_wrong-base.md
            issue: '%payload.pull_request.number%'
          # and we close the pull request, unmerged
          - type: closeIssue
            issue: '%payload.pull_request.number%'
      # If the user does everything right, we remove protections on the release branch so they can merge
      - type: removeBranchProtection
        branch: release-v1.0
      # We approve their pull request
      - type: createReview
        body: 03.2_approval.md
        event: APPROVE

  #7 - The user merges their pull request into the release branch
  - title: Merge the pull request
    description: Merge the pull request to update the release branch.
    event: pull_request.closed
    link: '{{ repoURL }}/pull/4'
    actions:
      # Because the event is the same for both, we make sure that the pull request is merged, and not just closed.
      - type: gate
        left: '%payload.pull_request.merged%'
        # If the pull request was closed with unmerged commits...
        else:
          # We reopen the pull request
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          # We comment and let them know that they should merge
          - type: respond
            with: 04.2early-close.md
            issue: '%payload.repository.pull_request.number%'
      # If the user does everything right, we create the next issue with instructions to create a pull request from the release branch into master
      - type: createIssue
        title: Create a release pull request
        body: 04.1_release-pr.md
        action_id: releaseIssue
      # We comment in the merged pull request, and point them to the new issue with instructions
      - type: respond
        issue: '{{ repoUrl }}/pull/4'
        with: 03.3_response.md
        data:
          url: '%actions.releaseIssue.data.html_url%'
      # We re-enable branch protection on the release branch
      - type: updateBranchProtection
        branch: release-v1.0

  #8 - The user opens a pull request from the release branch into master
  - title: Open a release pull request
    description: Create the release pull request with base as master, and compare as the release branch.
    event: pull_request.opened
    link: '{{ repoURL }}/issues/5'
    actions:
      # We check that the pull request has the correct "base" and "compare"
      - type: gate
        gates:
          - left: '%payload.pull_request.base.ref%'
            operator: ===
            right: master
          - left: '%payload.pull_request.base.ref%'
            operator: ===
            right: release-v1.0
        # If they do not have the correct base and compare fields...
        else:
          # We comment and tell them that the base and compare are wrong, and to try again
          - type: respond
            with: 05.2_wrong-base.md
          # We close the pull request
          - type: closeIssue
      # If they did everything right, we create a new pull request going into the release branch.
      # Currently the change is very minor, but it should make sense with the release.
      - type: createPullRequest
        title: More features for the next release
        body: 05.1_new-pr.md
        head: green-colors
        base: release-v1.0
        action_id: morefeaturesPR
      - type: mergePullRequest
        pullRequest: 6
      - type: octokit
        method: gitdata.deleteReference
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        ref: heads/green-colors
      - type: respond
        with: 06.1_successful-open.md
        issue: 7
      - type: respond
        with: 06.2_github-app.md
        issue: 7

  #9 - The user assigns themselves to the pull request
  - title: Automation and assignment
    description: Install the GitHub app to help with release notes, then assign yourself to the pull request.
    event: pull_request.assigned
    link: '{{ repoURL }}/pull/7'
    actions:
      - type: respond
        with: 06.3_response.md

  #10 - The user approves the branch merge into master
  - title: Approve the release
    description: Approve the release branch in the pull request to finalize this release.
    event: pull_request.review.submitted
    link: '{{ repoURL }}/pull/7'
    actions:
      # We check that the pull request was merged, not closed
      - type: gate
        left: '%payload.pull_request.merged%'
        # If it was closed, we...
        else:
          # Reopen the pull request
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          # We respond to ask them to merge instead of closing
          - type: respond
            with: 06.4_early-close.md
      # We merge the pull request into the master branch
      - type: mergePullRequest
      # We create a new issue asking them to turn the draft release into a published release
      - type: createIssue
        title: Finalize the release
        body: 07.1_finalize-release.md
        action_id: finalIssue
     # We comment in the merged pull request, pointing users to final instructions
      - type: respond
        with: 06.4_nice-merge.md
        data:
          url: '%actions.bugFixPR.data.html_url%'

  #11 - User creates a release from the draft
  - title: Finalize the release
    description: Complete the release by publishing the drafted release
    event: release.published
    link: '%actions.newPullRequest.data.html_url%'
    action_id: bugFixPR
    actions:
    ## Create a new PR for the hotfix
      - type: createPullRequest
        title: Accidental bugs
        body: 08.1_hotfix-intro.md
        head: bug-fix
        base: release-v1.0
        action_id: newPullRequest
      ## Suggest a change in the new PR
      ## This is kind of forced, so we don't need to keep it. I like the extra layer of interaction, though.
      - type: octokit
        method: pullRequests.createComment
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        number: '%payload.pull_request.number%'
        path: game.js
        body: |
          ```suggestion
              starCtx.fillStyle = "#000";
          ```
          ### :keyboard: Activity: Apply the suggestion
          1. Click **Apply suggestion**
          2. Enter a commit message
          3. Click **Commit changes**
          For more information about suggest changes, check out this [GitHub Help](https://help.github.com/articles/incorporating-feedback-in-your-pull-request) article.
        commit_id: '%payload.pull_request.head.sha%'
        position: 5

  #12 - User resolves the bug, then merges the pull request.
  - title: Resolve and merge
    description: Resolve the bug, then merge the fix into the release branch
    event: pull_request.closed
    link: '{{ repoURL }}/pull/8'
    actions:
    - type: gate
      left: '%payload.pull_request.merged%'
      # If the pull request was closed with unmerged commits...
      else:
        # We reopen the pull request
        - type: octokit
          method: issues.edit
          state: open
          owner: '%payload.repository.owner.login%'
          repo: '%payload.repository.name%'
          number: '%payload.repository.pull_request.number%'
        # We comment and let them know that they should merge
        - type: respond
          with: 04.2early-close.md
          issue: '%payload.repository.pull_request.number%'
    - type: respond
      body: 08.2_hotfix-merged-into-release.md

  #13 - User creates a new PR, then merges into master
  - title: Update master
    description: Merge your release branch changes into master
    event: pull_request.closed
    link: '{{ repoURL }}/pull/9'
    actions:
    - type: gate
      left: '%payload.pull_request.merged%'
      # If the pull request was closed with unmerged commits...
      else:
        # We reopen the pull request
        - type: octokit
          method: issues.edit
          state: open
          owner: '%payload.repository.owner.login%'
          repo: '%payload.repository.name%'
          number: '%payload.repository.pull_request.number%'
        # We comment and let them know that they should merge
        - type: respond
          with: 04.2early-close.md
          issue: '%payload.repository.pull_request.number%'
    - type: respond
      with: 09.1_last-release.md

  #14 - User creates hotfix release (and uses semantic versioning).
  - title: Finalize the hotfix release
    description: Complete the release by publishing the newest release
    event: release.published
    link: '%actions.finalIssue.data.html_url%'
    actions:
      - type: createIssue
        title: Contratulations
        body: 10.1_congratulations.md
