title: Creating a Release Based Workflow
tagline: Learn and practice a workflow based around creating releases on GitHub.
description: This course focuses on releases, and more complex branching strategies.
tags:
  - GitHub
template:
    name: release-based-workflow
    repo: release-workflow-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.1_welcome.md
  - type: octokit
    method: projects.createRepoProject
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    name: Release 1.0
    body: This project board tracks the steps necessary for Release 1.0.
    action_id: project
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: To Do
    action_id: columnToDo
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: In progress
    action_id: columnInProgress
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: Done
    action_id: columnDone
steps:

  #1
  - title: Create a beta release
    description: Create a beta release, or a pre-release, from the existing codebase.
    event: release.published
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createIssue
        title: Organizing a release
        body: 01.1_tracking-issue.md
        action_id: trackingIssue
      - type: updateBranchProtection
        branch: release-v1.0 #this doesn't use wildcards, but would it be possible?
      - type: respond
        issue: Welcome
        with: 01.2_next-step.md
        data:
          url: '%actions.trackingIssue.data.html_url%'
          releases: '{{ repoURl }}/releases'
      - type: closeIssue
        issue: Welcome

  #2
  - title: Prepare for the next release
    description: Add a card to the "in progress" column of the project board.
    event: project_card.created
    link: '{{ repoURL }}/projects/1'
    actions:
      - type: createIssue
        title: Please fix this bug
        body: 02.1_fix-bug.md
        action_id: fixbugIssue
      - type: respond
        with: 02.2_response-release.md

  #3
  - title: Fix the bug
    description: Create a branch, fix the bug, and open a pull request.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: gate
        left: '%payload.base.ref%'
        operator: ===
        right: release-v1.0
        else:
          - type: respond
            with: 03.2_wrong-base.md
          - type: closeIssue
            issue: '%payload.pull_request.url%'
      - type: createReview
        body: 03.1_approval.md
        event: APPROVE
      - type: octokit
        method: projects.createProjectCard
        column_id: '%actions.columnInProgress.data.id%'
        content_id: '%actions.fixbugIssue.data.id%'
        content_type: Issue
        action_id: fixbugIssueCard

  #4
  - title: Merge the pull request
    description: Merge the pull request to update the release branch.
    event: pull_request.closed
    link: '{{ repoURL }}/pull/4'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 04.3_early-close.md
      - type: createIssue
        title: Create a realease pull request
        body: 04.1_release-pr.md
        action_id: releaseIssue
      - type: respond
        issue: 4
        with: 04.2_response.md
        data:
          url: '%actions.releaseIssue.data.html_url%'
      - type: octokit
        method: projects.createProjectCard
        column_id: '%actions.columnDone.data.id%'
        content_id: '%actions.fixbugIssue.data.id%'
        content_type: Issue
        action_id: fixbugIssueCard
      - type: octokit
        method: projects.createProjectCard
        column_id: '%actions.columnInProgress.data.id%'
        content_id: '%actions.releaseIssue.data.id%'
        content_type: Issue
        action_id: releaseIssueCard
      - type: octokit
        method: projects.moveProjectCard
        card_id: '%actions.fixbugIssueCard.data.id%'
        position: 1
        column_id: '%actions.columnDone.data.id%'

  #5
  - title: Prepare to merge your release into master
    description: Create the release pull request with base as master, and compare as the release branch.
    event: pull_request.opened
    link: '{{ repoURL }}/issues/5'
    actions:
      - type: gate
        gates:
          - left: '%payload.base.ref%'
            operator: ===
            right: master
          - left: '%payload.head.ref%'
            operator: ===
            right: release-v1.0
        else:
          - type: respond
            with: 05.2_wrong-base.md
          - type: closeIssue
            issue: '%payload.pull_request.url%'
      - type: createPullRequest
        title: More features for the next release
        body: 05.1_new-pr.md
        head: feature-for-v1
        base: release-v1.0
        action_id: morefeaturesPR
      - type: respond
        with: 05.2_response.md
      - type: octokit
        method: projects.createProjectCard
        column_id: '%actions.columnInProgress.data.id%'
        content_id: '%actions.morefeaturesPR.data.id%'
        content_type: PullRequest
        action_id: morefeaturesPRCard

  #6
  - title: Review other work for this release
    description: The release will contain work from multiple pull requests. Approve the other open pull request to merge changes into the release branch.
    event: pull_request_review.submitted
    link: '{{ repoURL }}/pull/7'
    actions:
      - type: mergePullRequest
      - type: octokit
        method: gitdata.deleteReference
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        ref: feature-for-v1
      - type: createIssue
        title: Install a GitHub app to help with release notes
        body: 06.1_github-app.md
        action_id: appIssue
      - type: respond
        with: 06.2_response.md
        data:
          url: '%actions.appIssue.data.html_url%'
      - type: octokit
        method: projects.moveProjectCard
        card_id: '%actions.morefeaturesPRCard.data.id%'
        position: 1
        column_id: '%actions.columnDone.data.id%'

  #7
  - title: Automate your release notes
    description: Install the GitHub app to automate the production of release notes.
    event: issues.closed
    actions:
      - type: createReview
        body: 07.1_approve-release.md
        event: APPROVE
      - type: respond
        with: 07.2_point-to-pr.md
        data:
          url: '{{ repoURL }}/pull/6'
      - type: closeIssue
        issue: Install a GitHub app to help with release notes
      - type: octokit
        method: projects.createProjectCard
        column_id: '%actions.columnInProgress.data.id%'
        content_id: '%actions.appIssue.data.id%'
        content_type: Issue
        action_id: appIssueCard

  #8
  - title: Merge the release
    description: Merge the release branch in the pull request to finalize this release.
    event: pull_request.closed
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 08.1_early-close.md
      - type: createIssue
        title: Finalize the release
        body: 08.2_finalize-release.md
        action_id: finalIssue
      - type: respond
        with: 08.3_nice-merge.md
        data:
          url: '%actions.finalIssue.data.html_url%'
      - type: octokit
        method: projects.moveProjectCard
        card_id: '%actions.appIssueCard.data.id%'
        position: 1
        column_id: '%actions.columnDone.data.id%'

  #9
  - title: Finalize the release
    description: Complete the release by publishing the drafted release
    event: release.published
    link: '%actions.finalIssue.data.html_url%'
    actions:
      - type: respond
        with: 09.1_congratulations.md
        issue: Finalize the release
      - type: octokit
        method: projects.moveProjectCard
        card_id: '%actions.releaseIssueCard.data.id%'
        position: 1
        column_id: '%actions.columnDone.data.id%'
