title: Creating a Release Based Workflow
tagline: Learn and practice a workflow based around creating releases on GitHub.
description: This course focuses on releases, and more complex branching strategies.
tags:
  - GitHub
template:
  # Template repository is currently only a README.md
    name: release-based-workflow
    repo: release-workflow-template
before:
  # enable branch protection
  - type: updateBranchProtection
  - type: updateBranchProtection
    branch: release-v1.0
  # creating a welcome issue that will have the user's first instructions
  - type: createIssue
    title: Welcome
    body: 00.1_welcome.md
  # octokit method to create a project board for the user to use throughout the course, and methods following to create each column
  - type: octokit
    method: projects.createRepoProject
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    name: Release 1.0
    body: This project board tracks the steps necessary for Release 1.0.
    action_id: project
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: To Do
    action_id: columnToDo
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: In progress
    action_id: columnInProgress
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: Done
    action_id: columnDone
steps:

  #1 - ask the user to create a beta release from the most recent commit on master
  - title: Create a beta release
    description: Create a beta release, or a pre-release, from the existing codebase.
    event: release.published
    link: '{{ repoUrl }}/issues/1'
    actions:
      # creating an issue with the next instructions, giving information about how to organize releases, and instructing user to add this card to the project board
      - type: createIssue
        title: Organizing a release
        body: 01.1_tracking-issue.md
        action_id: trackingIssue
      # responding in the first welcome issue, pointing the user to the next issue just created
      - type: respond
        issue: Welcome
        with: 01.2_next-step.md
        data:
          url: '%actions.trackingIssue.data.html_url%'
          releases: '{{ repoURl }}/releases'
      # closes the welcome issue
      - type: closeIssue
        issue: Welcome

  #2 - The user should have moved the 2nd issue we created, "Organizing a release", to the "In progress" column of the project board
  - title: Prepare for the next release
    description: Add a card to the "in progress" column of the project board.
    event: project_card.created
    link: '{{ repoURL }}/projects/1'
    actions:
      # creating a third issue for the user, asking them to go through the GitHub flow to make a change
      - type: createIssue
        title: Please fix this bug
        body: 02.1_fix-bug.md
        action_id: fixbugIssue
      # We want to track the progress of all things that we can in the project board, so as soon as we created the issue, we move it to the project board
      #- type: octokit
      #  method: projects.createProjectCard
      #  column_id: '%actions.columnInProgress.data.id%'
      #  content_id: '%actions.fixbugIssue.data.id%'
      #  content_type: Issue
      #  action_id: fixbugIssueCard
      # commenting in the organizational issue, pointing user to next bug. Leaving issue open, mapping "tracking issue" concept
      - type: respond
        with: 02.2_response-release.md
        issue: Organizing a release

  #3 - User creates a branch making a change and opens a pull request against `base: release-v1.0`
  - title: Fix the bug
    description: Create a branch, fix the bug, and open a pull request.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/3'
    actions:
      # We make sure that the user's pull request has the base set to `release-v1.0`
      - type: gate
        left: '%payload.base.ref%'
        operator: ===
        right: release-v1.0
        # If the user opened a pull request to master instead...
        else:
          # we comment and tell them that they should try again
          - type: respond
            with: 03.2_wrong-base.md
            issue: '%payload.pull_request.number%'
          # and we close the pull request, unmerged
          - type: closeIssue
            issue: '%payload.pull_request.url%'
      # If the user does everything right, we remove protections on the release branch so they can merge
      - type: removeBranchProtection
        branch: release-v1.0
      # We approve their pull request
      - type: createReview
        body: 03.1_approval.md
        event: APPROVE

  #4 - The user merges their pull request into the release branch
  - title: Merge the pull request
    description: Merge the pull request to update the release branch.
    event: pull_request.closed
    link: '{{ repoURL }}/pull/4'
    actions:
      # Because the event is the same for both, we make sure that the pull request is merged, and not just closed.
      - type: gate
        left: '%payload.pull_request.merged%'
        # If the pull request was closed with unmerged commits...
        else:
          # We reopen the pull request
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          # We comment and let them know that they should merge
          - type: respond
            with: 04.3_early-close.md
            issue: '%payload.repository.pull_request.number%'
      # If the user does everything right, we create the next issue with instructions to create a pull request from the release branch into master
      - type: createIssue
        title: Create a realease pull request
        body: 04.1_release-pr.md
        action_id: releaseIssue
      # We move the new issue for creating a release branch into the "in progress" column of the project board
      #- type: octokit
      #  method: projects.createProjectCard
      #  column_id: '%actions.columnInProgress.data.id%'
      #  content_id: '%actions.releaseIssue.data.id%'
      #  content_type: Issue
      #  action_id: releaseIssueCard
      # We comment in the merged pull request, and point them to the new issue with instructions
      - type: respond
        issue: 4
        with: 04.2_response.md
        data:
          url: '%actions.releaseIssue.data.html_url%'
      # We move the card for the bug fix into the "done" column on the project board
      #- type: octokit
      #  method: projects.moveProjectCard
      #  card_id: '%actions.fixbugIssueCard.data.id%'
      #  position: 1
      #  column_id: '%actions.columnDone.data.id%'
      # We re-enable branch protection on the release branch
      - type: updateBranchProtection
        branch: release-v1.0

  #5 - The user opens a pull request from the release branch into master
  - title: Prepare to merge your release into master
    description: Create the release pull request with base as master, and compare as the release branch.
    event: pull_request.opened
    link: '{{ repoURL }}/issues/5'
    actions:
      # We check that the pull request has the correct "base" and "compare"
      - type: gate
        gates:
          - left: '%payload.base.ref%'
            operator: ===
            right: master
          - left: '%payload.head.ref%'
            operator: ===
            right: release-v1.0
        # If they do not have the correct base and compare fields...
        else:
          # We comment and tell them that the base and compare are wrong, and to try again
          - type: respond
            with: 05.2_wrong-base.md
            issue: '%payload.repository.pull_request.number%'
          # We close the pull request
          - type: closeIssue
            issue: '%payload.pull_request.url%'
      # If they did everything right, we create a new pull request going into the release branch.
      # Currently the change is very minor, but it should make sense with the release.
      - type: createPullRequest
        title: More features for the next release
        body: 05.1_new-pr.md
        head: feature-for-v1
        base: release-v1.0
        action_id: morefeaturesPR
      # We make a card for the new pull request in the "in progress" column
      #- type: octokit
      #  method: projects.createProjectCard
      #  column_id: '%actions.columnInProgress.data.id%'
      #  content_id: '%actions.morefeaturesPR.data.id%'
      #  content_type: PullRequest
      #  action_id: morefeaturesPRCard
      # We reply in the new pull request they created and point them to the new PR we just made
      - type: respond
        with: 05.2_response.md
        issue: '%payload.repository.pull_request.number%'

  #6 - The user should review the pull request
  - title: Review other work for this release
    description: The release will contain work from multiple pull requests. Approve the other open pull request to merge changes into the release branch.
    event: pull_request_review.submitted
    link: '{{ repoURL }}/pull/7'
    actions:
      # We merge the pull request into the release branch
      - type: mergePullRequest
      # We delete the feature branch
      - type: octokit
        method: gitdata.deleteReference
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        ref: feature-for-v1
      # We create a new issue with instructions for release notes
      - type: createIssue
        title: Install a GitHub app to help with release notes
        body: 06.1_github-app.md
        action_id: appIssue
      # We create a card for the new issue in the "in progress" column
      #- type: octokit
      #  method: projects.createProjectCard
      #  column_id: '%actions.columnInProgress.data.id%'
      #  content_id: '%actions.appIssue.data.id%'
      #  content_type: Issue
      #  action_id: appIssueCard
      # We respond in the merged pull request pointing the user to the new issue
      - type: respond
        with: 06.2_response.md
        issue: '%payload.repository.pull_request.number%'
        data:
          url: '%actions.appIssue.data.html_url%'

  #7 - The user installs the GitHub app, and closes this issue.
  - title: Automate your release notes
    description: Install the GitHub app to automate the production of release notes.
    event: issues.closed
    link: '{{ repoUrl }}/issue/8'
    actions:
      # We approve the release pull request
      - type: createReview
        body: 07.1_approve-release.md
        event: APPROVE
      # We remove branch protections so they can merge
      - type: removeBranchProtection
      # We comment in the release note issue, pointing to the release pull request
      - type: respond
        with: 07.2_point-to-pr.md
        data:
          url: '{{ repoURL }}/pull/6'
      # We move the app issue to the done column of the project board
      #- type: octokit
      #  method: projects.moveProjectCard
      #  card_id: '%actions.appIssueCard.data.id%'
      #  position: 1
      #  column_id: '%actions.columnDone.data.id%'

  #8 - The user merges the release branch into master
  - title: Merge the release
    description: Merge the release branch in the pull request to finalize this release.
    event: pull_request.closed
    link: '{{ repoURL }}/pull/7'
    actions:
      # We check that the pull request was merged, not closed
      - type: gate
        left: '%payload.pull_request.merged%'
        # If it was closed, we...
        else:
          # Reopen the pull request
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          # We respond to ask them to merge instead of closing
          - type: respond
            with: 08.1_early-close.md
      # We create a new issue asking them to turn the draft release into a published release
      - type: createIssue
        title: Finalize the release
        body: 08.2_finalize-release.md
        action_id: finalIssue
      # We put that issue "In progress" on the project board
      #- type: octokit
      #  method: projects.createProjectCard
      #  column_id: '%actions.columnInProgress.data.id%'
      #  content_id: '%actions.finalIssue.data.id%'
      #  content_type: Issue
      #  action_id: finalIssueCard
     # We comment in the merged pull request, pointing users to final instructions
      - type: respond
        with: 08.3_nice-merge.md
        data:
          url: '%actions.finalIssue.data.html_url%'

  #9 - User creates a release from the draft
  - title: Finalize the release
    description: Complete the release by publishing the drafted release
    event: release.published
    link: '%actions.finalIssue.data.html_url%'
    actions:
      # We comment in the issue, congratulating them
      - type: respond
        with: 09.1_congratulations.md
        issue: Finalize the release
      # We close the issue because we won't use it anymore
      - type: closeIssue
        issue: Finalize the release
      # We move the final card to the done column in the project board
      #- type: octokit
      #  method: projects.moveProjectCard
      #  card_id: '%actions.finalIssueCard.data.id%'
      #  position: 1
      #  column_id: '%actions.columnDone.data.id%'
      # We also close the tracking issue
      - type: closeIssue
        issue: Organizing a release
      # We move the tracking issue to "done" on the project board
      #- type: octokit
      #  method: projects.moveProjectCard
      #  card_id: '%actions.releaseIssueCard.data.id%'
      #  position: 1
      #  column_id: '%actions.columnDone.data.id%'
