title: Creating a Release Based Workflow
tagline: Learn and practice a workflow based around creating releases on GitHub.
description: This course focuses on releases, and more complex branching strategies.
tags:
  - GitHub
template:
    name: release-based-workflow
    repo: release-workflow-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.1_welcome.md
  - type: octokit
    method: projects.createRepoProject
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    name: Release 1.0
    body: This project board tracks the steps necessary for Release 1.0.
    action_id: project
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: To Do
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: In progress
  - type: octokit
    method: projects.createProjectColumn
    project_id: '%actions.project.data.id%'
    name: Done
steps:

  #1
  - title: Create a beta release
    description: Create a beta release, or a pre-release, from the existing codebase.
    event: release.published
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createIssue
        title: Organizing a release
        body: 01.1_tracking-issue.md
        action_id: trackingIssue
      - type: #  create a release branch using the `release-*` convention
      - type: # set up branch protections using wildcards for branch name
      - type: respond
        issue: Welcome
        with: 01.2_next-step.md
        data:
          url: '%actions.trackingIssue.data.html_url%'
          releases: '{{ repoURl }}/releases'
      - type: closeIssue
        issue: Welcome

  #2
  - title: Prepare for the next release
    description: Add a card to the "in progress" column of the project board.
    event: project_card.created
    link: '{{ repoURL }}/projects/1'
    actions:
      - type: createIssue
        title: Please fix this bug
        body: 02.1_fix-bug.md
      - type: response
        with: 02.2_response-release.md
      # TODO: what if the bug is a hotfix that could also be applied into master? (note: @briana is not sure what was meant by this original todo)

  #3
  - title: Fix the bug
    description: Create a branch, fix the bug, and open a pull request.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: # validate base branch is the branch created in step 1
      - type: # approval,
        with: 03.1_approval.md
      - type: # update project board

  #4
  - title: Merge the pull request
    description: Merge the pull request to update the release branch.
    event: pull_request.closed
    link: '{{ repoURL }}/pull/4'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 04.3_early-close.md
      - type: createIssue
        title: Create a realease pull request
        body: 04.1_release-pr.md
        action_id: releaseIssue
      - type: response
        issue: 4
        with: 04.2_response.md
        data:
          url: '%actions.releaseIssue.data.html_url%'
      - type: # update project board

    #5
    - title: Prepare to merge your release into master
      description: Create the release pull request with base as master, and compare as the release branch.
      event: pull_request.opened
      link: '{{ repoURL }}/issues/5'
      actions:
        - type: gate #check the proper base (master), proper branch (created step 1) being PRed
        - type: # create 1+ PRs (and project cards, etc) of other work that will go into the release branch
          title: More features for the next release
          body: 05.1_new-pr.md
          head: #new branch we need to create
          base: #branch created in PR
        - type: response
          with: 05.2_response.md
      # update project board

    #6
    - title: Review other work for this release
      description: The release will contain work from multiple pull requests. Approve the other open pull request to merge changes into the release branch.
      event: pull_request_review.submitted
      link: '{{ repoURL }}/pull/7'
      actions:
        - type: mergePullRequest
        - type: octokit
          method: gitdata.deleteReference
          owner: '%payload.repository.owner.login%'
          repo: '%payload.repository.name%'
          ref: #whatever we named it
        - type: createIssue
          title: Install a GitHub app to help with release notes
          body: 06.1_github-app.md
          action_id: appIssue
        - type: response
          with: 06.2_response.md
          data:
            url: '%actions.appIssue.data.html_url%'
        # update project board

    #7
    - title: Automate your release notes
      description: Install the GitHub app to automate the production of release notes.
      event: #TODO
      actions:
        - type: createReview
          body: 07.1_approve-release.md
          event: APPROVE
        - type: response
          with: 07.2_point-to-pr.md
          data:
            url: '{{ repoURL }}/pull/6'
        - type: closeIssue
          issue: Install a GitHub app to help with release notes
        # update project board

    #8
    - title: Merge the release
      description: Merge the release branch in the pull request to finalize this release.
      event: pull_request.closed
      actions:
        - type: gate
          left: '%payload.pull_request.merged%'
          else:
            - type: octokit
              method: issues.edit
              state: open
              owner: '%payload.repository.owner.login%'
              repo: '%payload.repository.name%'
              number: '%payload.repository.pull_request.number%'
            - type: respond
              with: 08.1_early-close.md
        - type: createIssue
          title: Finalize the release
          body: 08.2_finalize-release.md
          action_id: finalIssue
        - type: response
          with: 08.3_nice-merge.md
          data:
            url: '%actions.finalIssue.data.html_url%'

    #9
    title: Finalize the release
    description: Complete the release by publishing the drafted release
    event: #??
    link: '%actions.finalIssue.data.html_url%'
    actions:
      - type: response
        with: 09.1_congratulations.md
        issue: Finalize the release
